version: "3.7"
services:
  api:
    build:
      context: ./travelblog-api
      dockerfile: Dockerfile.dev
    environment:
      - "DB_URL=mongodb://mongo:27017/test"
    ports:
      - "3000:3000"
    depends_on:
      - mongo
  mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017"
